/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package th6;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class JFTinhTienTaxi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFTinhTienTaxi.class.getName());

    /**
     * Creates new form JFTinhTienTaxi
     */
    public JFTinhTienTaxi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSoKm = new javax.swing.JLabel();
        jTextFieldSoKm = new javax.swing.JTextField();
        jLabelTien = new javax.swing.JLabel();
        jTextFieldTien = new javax.swing.JTextField();
        jButtonTinhTien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSoKm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSoKm.setText("Số km");

        jTextFieldSoKm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTien.setText("Số tiền");

        jTextFieldTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButtonTinhTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonTinhTien.setText("Tính tiền");
        jButtonTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTinhTienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSoKm)
                        .addGap(53, 53, 53)
                        .addComponent(jTextFieldSoKm, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTien)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonTinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTien))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSoKm)
                    .addComponent(jTextFieldSoKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonTinhTien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTien)
                    .addComponent(jTextFieldTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTinhTienActionPerformed
        try {
        double km = Double.parseDouble(jTextFieldSoKm.getText());

        if (km < 0) {
            JOptionPane.showMessageDialog(this, "Nhập dữ liệu sai!");
        } else {
            double tien = km * 10000;
            jTextFieldTien.setText(String.valueOf(tien));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ!");
    }
    }//GEN-LAST:event_jButtonTinhTienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFTinhTienTaxi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTinhTien;
    private javax.swing.JLabel jLabelSoKm;
    private javax.swing.JLabel jLabelTien;
    private javax.swing.JTextField jTextFieldSoKm;
    private javax.swing.JTextField jTextFieldTien;
    // End of variables declaration//GEN-END:variables
}
